canonical: https://gematik.de/fhir/isik
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
dependencies:
  de.basisprofil.r4: 1.5.0-ballot3
  de.gematik.isik-basismodul: 4.0.0-rc2